receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:
    send_batch_size: 100000

exporters:
  clickhouse:
    endpoint: tcp://clickhouse:9000
    database: default
    username: default
    password: password


service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [clickhouse]
